import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "./global/Container";
import Navbar from "./navbar/Navbar";
import { ClerkProvider } from '@clerk/nextjs';
import Providers from './providers';
import Footer from "./global/Footer";

const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Licenta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className} suppressHydrationWarning>
          <Providers>
            <Navbar />
            <Container>{children}</Container>
            <Footer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
